# Generated by Django 3.1.6 on 2021-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210218_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Just a freelancer looking to earn some extra money by offering services', help_text='Help people get to know you better. Remember a good bio attracts me clients!'),
        ),
    ]
