# Generated by Django 3.1.6 on 2021-02-23 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, max_length=130)),
                ('intro', models.CharField(max_length=100, unique=True)),
                ('pricing', models.IntegerField()),
                ('detail', django_summernote.fields.SummernoteTextField()),
                ('image', models.ImageField(default='default.png', upload_to='services')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.category')),
            ],
            options={
                'verbose_name_plural': 'Services on Offer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='What was the project all about? Explain in detail')),
                ('image', models.ImageField(default='default.png', upload_to='projects')),
                ('url', models.URLField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Previous Projects',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The possible question that a client could ask you', max_length=150)),
                ('answer', models.TextField(help_text='The response to the question above')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Which service is this FAQ linked to?', on_delete=django.db.models.deletion.CASCADE, to='careers.services')),
            ],
            options={
                'verbose_name_plural': 'Frequently Asked Questions',
            },
        ),
    ]
