# Generated by Django 3.1.6 on 2021-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
