# Generated by Django 3.1.6 on 2021-03-01 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(help_text='Which service is this FAQ linked to?', on_delete=django.db.models.deletion.CASCADE, related_name='faq_service', to='careers.services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
