# Generated by Django 3.1.6 on 2021-02-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('careers', '0002_auto_20210222_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
