# Generated by Django 3.1.6 on 2021-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20210222_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
