# Generated by Django 3.1.6 on 2021-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_auto_20210220_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='default.png', upload_to='services'),
        ),
    ]
