# Generated by Django 3.1.6 on 2021-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
