# Generated by Django 3.1.6 on 2021-02-22 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0005_auto_20210222_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='author_service',
        ),
        migrations.AlterField(
            model_name='services',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
