# Generated by Django 3.1.6 on 2021-02-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210218_1923'),
        ('careers', '0007_auto_20210220_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
