# Generated by Django 3.1.6 on 2021-02-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='author',
        ),
    ]
