# Generated by Django 3.1.6 on 2021-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20210211_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='engtype_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='name_2',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='nl_name_2',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='type_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='varname_2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
