# Generated by Django 3.1.6 on 2021-02-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_category_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.category'),
        ),
    ]
