# Generated by Django 3.1.6 on 2021-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20210213_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(help_text='Provide a brief description about your map, how it helps and what is being displayed'),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(help_text='Place the map title here', max_length=30),
        ),
    ]
