# Generated by Django 3.1.6 on 2021-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20210213_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='link',
            field=models.URLField(help_text='You link should be an https link. E.g https://example.com'),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(help_text='Place the map title here', max_length=30, unique=True),
        ),
    ]
