# Generated by Django 3.1.6 on 2021-02-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20210213_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='embed_type',
            field=models.CharField(blank=True, choices=[('arcgis', 'arcgis'), ('google', 'google'), ('openstreet', 'openstreet'), ('image', 'image')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='link',
            field=models.URLField(help_text='Your link should be an https link. E.g https://example.com', verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Bucketlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(help_text='Provide a detailed explanation about the map in order for the mappers to get a clear understanding of what you are looking for')),
                ('reference', models.URLField(help_text='Have you seen such a map elsewhere? If yes please provide a link to the source as this will also help the mappers visualize easily', null=True)),
                ('category', models.ForeignKey(help_text='To which category does this map belong to?', on_delete=django.db.models.deletion.CASCADE, to='collector.category')),
            ],
            options={
                'verbose_name_plural': 'Maps BucketList',
            },
        ),
    ]
