# Generated by Django 3.1.6 on 2021-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_auto_20210214_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='COVID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('description', models.TextField(help_text='The detailed description of the tool')),
                ('embed_type', models.CharField(blank=True, choices=[('dashboard', 'dashboard'), ('webapp', 'webapp'), ('webmap', 'webmap'), ('survey123', 'survey123')], max_length=50, null=True)),
                ('link', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'COVID-19 Resources',
            },
        ),
        migrations.AlterField(
            model_name='map',
            name='embed_type',
            field=models.CharField(blank=True, choices=[('arcgis', 'ArcGIS'), ('google', 'Google'), ('openstreet', 'OpenStreet'), ('image', 'Image')], max_length=50, null=True),
        ),
    ]
