# Generated by Django 3.1.6 on 2021-02-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20210216_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='external_resource',
            field=models.URLField(blank=True, help_text='Specify the original link of the resource that you have just added to the list', null=True),
        ),
    ]
