# Generated by Django 3.1.6 on 2021-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_covid_external_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='embed_type',
            field=models.CharField(blank=True, choices=[('dashboard', 'dashboard'), ('webapp', 'webapp'), ('webmap', 'webmap'), ('survey123', 'survey123'), ('repository', 'repository')], max_length=50, null=True),
        ),
    ]
